#!/bin/bash

# Authenticate with Terminus and pull down drush aliases
echo "Authenticating to Pantheon"
if [ -z "${PANTHEON_TOKEN}" ]; then
  # Backwards compatibility pre-machine token.
  terminus auth login ${PANTHEON_EMAIL} --password=${PANTHEON_PASS}
  echo "Warning: authentication via e-mail and password is deprecated and will be removed in a future release."
  echo "Please start using machine tokens via the PANTHEON_TOKEN environment variable."
else
  echo "...Using a machine token."
  terminus auth login --machine-token=${PANTHEON_TOKEN}
fi

# Return MySQL connection info from Pantheon via Terminus.
echo "Returning MySQL credentials from Pantheon."
MYSQL_STRING=$(terminus site connection-info --site=${PANTHEON_SITE} --env=${PANTHEON_ENV} --field=mysql_url);

if [[ "$MYSQL_STRING" =~ mysql:\/\/([^[:space:]]*):([^[:space:]]*)@([^[:space:]]*):([0-9]*)\/([^[:space:]]*) ]]; then
  echo "Extracting MySQL credentials"
  export PANTHEON_DB_UN=${BASH_REMATCH[1]}
  export PANTHEON_DB_PW=${BASH_REMATCH[2]}
  export PANTHEON_DB_HOST=${BASH_REMATCH[3]}
  export PANTHEON_DB_PORT=${BASH_REMATCH[4]}
fi

echo "Starting MySQL proxy"
mysql-proxy --keepalive --log-level=critical --proxy-address=0.0.0.0:${PROXY_DB_PORT} --proxy-backend-addresses=${PANTHEON_DB_HOST}:${PANTHEON_DB_PORT} --proxy-lua-script=/opt/auth.lua --plugins=proxy
